### ISSUE TITLE
Incorrect Time Scaling on PPK2

### ISSUE THREAD

**Issue by joshbohmer** [NordicSemiconductor/pc-nrfconnect-ppk#141] opened 2021-01-05 00:49 UTC
Time Scaling is incorrect. See attached

Each event shown here is ~40s duration & ~5minute between starts. Power Profiler says 6.34s & 48.8s

![image](https://user-images.githubusercontent.com/3621222/103593916-0cbe4300-4f47-11eb-9946-4c7d2152e7c5.png)
![image](https://user-images.githubusercontent.com/3621222/103593923-15af1480-4f47-11eb-996d-67b71b128ce4.png)
![image](https://user-images.githubusercontent.com/3621222/103593978-3d05e180-4f47-11eb-88ad-2449105ed8eb.png)

**Comment by wlgrd** [comment] 2021-01-05 10:16
Thank you for reporting! Is this happening all the time, also for shorter events? You should see it quite immediately, since this is really a long way off! Also, try and zoom in on the chart and see if there are any data points that seem missing. 
We've seen that if sampling with a large window for a long time, causing the software to display a lot of samples continuously, this behavior might happen (but on a much smaller scale) but haven't been able to reproduce properly. Please also try to sample the same application, but with a smaller window. When you have the data you need, stop sampling and then zoom out to the full view to measure the timing again. 

Also, please post your system specs. Thank you.

**Comment by joshbohmer** [comment] 2021-01-05 14:05
Issue happens immediately on opening the Profiler window & starting the sample. See below.

![image](https://user-images.githubusercontent.com/3621222/103655205-d4eee400-4fb6-11eb-9938-aed7182738ec.png)

In this example 1minute is reported as 10s on the time scale.

I've also tried a small window & same issue as you can see

My system is as follows...
Ryzen 1600, 32GB RAM, 1TB NVME SSD, 8GB 1070, Win 10 Pro

**Comment by wlgrd** [comment] 2021-01-06 08:58
Not good... Can you zoom way in on the chart, like 500µs window size so you see the individual samples? 
![image](https://user-images.githubusercontent.com/1696969/103749359-b49a4600-5005-11eb-9027-ae1c8c887402.png)
Also try with power off, just for brevity's sake.

**Comment by joshbohmer** [comment] 2021-01-06 09:28
Zoomed In
![image](https://user-images.githubusercontent.com/3621222/103750532-db349d00-5056-11eb-9eb8-b61942a13184.png)

Power Off
![image](https://user-images.githubusercontent.com/3621222/103750574-ebe51300-5056-11eb-987e-fd32bd09af90.png)

Below DUT is a Nordic nRD52 DK w/ nRF Connect Bluetooth Low Energy Firmware as pictured.
![image](https://user-images.githubusercontent.com/3621222/103751318-05d32580-5058-11eb-9d7a-75a15eaaa8f1.png)
![image](https://user-images.githubusercontent.com/3621222/103752135-38315280-5059-11eb-8109-1348d264031d.png)
Same Issue

My Windows 10 region is set to Australia AU in case its a date/time formatting issue.

Requested Below w/logs (power on/off every 2 seconds)
![20210106_194221](https://user-images.githubusercontent.com/3621222/103752339-85152900-5059-11eb-9f1b-f9d87be8abea.jpg)


[2021-01-06T09_04_47.147Z-log.txt](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/files/5774896/2021-01-06T09_04_47.147Z-log.txt)

**Comment by wlgrd** [comment] 2021-01-06 09:41
Thank you. For the feature, please enable the timestamps from the sidebar as well so we can see it along the x-axis:) I see that your zoomed in window measures exactly as expected. Every sample is 10µs, and you mark 12 samples = 120µs. This rules out any date/time formatting issue. I also see that you didn't zoom in on the plot where you power toggle, so I need you to do that, maybe look around a little to see if there are any gaps in the data set. Also, just start sampling and stop some seconds later, so we can correlate the whole range of timestamps along the x-axis with the log.

**Comment by joshbohmer** [comment] 2021-01-06 10:51
Short Sample (10s)
![image](https://user-images.githubusercontent.com/3621222/103760218-b6472680-5064-11eb-95c3-61a04972098e.png)
Log
[2021-01-06T10_44_21.869Z-log.txt](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/files/5775322/2021-01-06T10_44_21.869Z-log.txt)
Data Export
[ppk-20210106T104921_csv.txt](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/files/5775327/ppk-20210106T104921_csv.txt)
Zoomed In
![image](https://user-images.githubusercontent.com/3621222/103760465-1047ec00-5065-11eb-98a9-17bc92f4617e.png)

**Comment by bencefr** [comment] 2021-01-06 11:21
@joshbohmer , the "Short sample (10s)" screenshot does not show the 10s sample in the chart, please navigate the chart to the relevant 10s area. Please note the state of the LIVE VIEW toggle (which is off on the screenshot). If you toggle that on, the chart would be aligned to the latest data. I suggest to first click on the [10s] button, toggle LIVE VIEW on. So far I can't positively judge if there is anything wrong with the app.

**Comment by joshbohmer** [comment] 2021-01-06 11:26
That is the entire chart, 10s is shown as ~1.6s

Same data, with Live View enabled as proof
![image](https://user-images.githubusercontent.com/3621222/103763482-ce6d7480-5069-11eb-89f3-6b9861621244.png)

**Comment by wlgrd** [comment] 2021-01-06 11:31
Do you observe the incoming data as one to one with the DUT connection (like unplugging, turning it on and off)? Just to know if it is just the time axis that is wrong, but also the timing of the incoming samples.

**Comment by bencefr** [comment] 2021-01-06 11:31
I see. Could you please press Ctrl+Alt+Shift+L, so the Export button changes to Save/Export, then click on it and choose Save. Please share the saved PPK file.

**Comment by joshbohmer** [comment] 2021-01-06 11:36
@wlgrd The data shown on the graph is correct & 1:1 with what's expected. It's just the time scale which shows incorrect & (i think) makes the power usage numbers incorrect. the nRF52 DK should not be using ~10mA

@bencefr Attached
[ppk-20210106T113219.zip](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/files/5775514/ppk-20210106T113219.zip)

**Comment by joshbohmer** [comment] 2021-01-06 11:47
Video Attached, hopefully it helps

https://user-images.githubusercontent.com/3621222/103765355-fad6c000-506c-11eb-8571-c17e27c7458b.mp4

**Comment by bencefr** [comment] 2021-01-06 11:57
There is a massive data loss from the PPK2 to the app somewhere. We have experienced data loss, but not to this nature. Do you have anything unusual in your setup? If you can, please connect the PPK2 to an other, preferably USB3 port. Avoid using HUBs and try changing the cable. Don't use virtual machine environments.

**Comment by joshbohmer** [comment] 2021-01-06 12:01
It plugs directly into a USB3 motherboard port. No hubs. Nothing unusual I can think of.

**Comment by joshbohmer** [comment] 2021-01-06 12:08
Different Cable & Different USB3 Port on the Motherboard

![image](https://user-images.githubusercontent.com/3621222/103767078-e811ba80-506f-11eb-9b17-251e510cc118.png)

**Comment by wlgrd** [comment] 2021-01-06 12:15
Can you try in a USB 2.0 port?

**Comment by joshbohmer** [comment] 2021-01-06 12:15
For data loss its VERY consistent. I would expect different results every time if it were data loss. This is always the same. ~6s (Real) = ~1s (Chart)

**Comment by wlgrd** [comment] 2021-01-06 12:15
Can you try in a USB 2.0 port?

**Comment by wlgrd** [comment] 2021-01-06 12:17
Also, if possible, please try with a different computer altogether. This is really interesting, and I guess more people will experience a similar issue if this is some hardware compatibility issue. Your findings are appreciated

**Comment by joshbohmer** [comment] 2021-01-06 12:19
So on a USB2 ports I get this... 2s = 1s - Which is an improvement & clearly a hardware (or driver) issue then.

![image](https://user-images.githubusercontent.com/3621222/103767899-6327a080-5071-11eb-923c-14a4355ea861.png)

**Comment by wlgrd** [comment] 2021-01-08 09:17
Thank you for your reports. We will work to reproduce this locally and get back to you.

**Comment by wlgrd** [comment] 2021-01-14 09:54
Can you share information about your chipset?

**Comment by wlgrd** [comment] 2021-02-15 09:39
@joshbohmer Just bumping to get some information about your chipset. Also, please check if 3.1 solves this issue for you.

**Comment by kareszv13** [comment] 2021-03-03 13:01
I have similar issue (v3.1.0)

# nRFConnect System Report - 2021-03-03T12-46-14.367Z

- System:     Gigabyte Technology Co., Ltd. B450M S2H
- BIOS:       American Megatrends Inc. ALASKA - 1072009
- CPU:        1 x AMD Ryzen 7 2700X Eight-Core Processor 3.7 GHz 16 cores (8 physical)
- Memory:     6.6 GB free of 15.9 GB total
- Filesystem: C: (NTFS) 418.4 GB 88.2% used

- OS:         Microsoft Windows 10 Education (10.0.19042) win32 ia32

- Versions
    - kernel: 10.0.19042
    - git: 2.24.1.windows.2
    - node: 12.13.0
    - python: 3.8.2
    - python3: 

- Connected devices:
    - COM3: C43C9BA7C356

**Comment by rodrigobrochado** [comment] 2022-01-31 21:22
I'm having the same problem with a PPK (old one) attached on top of a nrf52840-DK. I have already tested with different versions for nRF connect (3.9.3, 3.71 and 3.6.1) and Power Profiler app, and flashed different firmwares on the PPK nrf52832 using those versions. Also tested on Ubuntu 21.10, 20.10 (it has already worked on 20.10 before) and on a different notebook with Windows 10.

I'm kind of skeptical, but due the age of both boards, could this problem be caused by hardware damage? @wlgrd

**Comment by wlgrd** [comment] 2022-02-01 08:05
So you have incorrect time scaling as well? That's an issue we haven't seen with the PPK, only the PPK2. The time scale should definitely not be affected by the age of the hardware.

**Comment by rodrigobrochado** [comment] 2022-02-01 11:56
Yes, incorrect time scaling. I'm also not getting correct and reproducible measurements values, that's why i though of hardware damage. e.g.: I normally get constant 3mA for an erased nrf52840 chip, but I'm getting some strange behavior:
![image](https://user-images.githubusercontent.com/50054071/151963077-330043fa-c277-47a3-a844-25a9e7021371.png)

Sometimes it even gets constant 25 uA for the erased chip...

**Comment by rodrigobrochado** [comment] 2022-03-04 17:23
New PPK2 working fine on same PC and settings (had just to update [udev rules](https://github.com/NordicSemiconductor/nrf-udev)). It seems that both our old ppk and nrf DK was not working as expected. I would blame sea air corrosion...

**Comment by wlgrd** [comment] 2022-03-07 11:43
Strange indeed. Can you give me the label information of both the working and failing PPK2's that you have?

**Comment by rodrigobrochado** [comment] 2022-03-07 12:45
The failing one is a PPK1, not PPK2, mounted on top of a DK. 
PPK1 label: PCA63511 Rev 1.1.0, 2018.44
DK label: PCA10056 1.1.0, 2019.11

**Comment by wlgrd** [comment] 2022-03-07 13:30
Ah, of course. Sorry for that. It should definitely not be caused by aging hardware at least. For the PPK1 case, there are aspects of it that we cannot control due to using the debugger firmware from SEGGER to provide the transport  of the data. Will keep an eye out for more cases, so thank you for reporting it.

**Comment by wlgrd** [comment] 2022-03-07 13:31
Since OP hasn't responded in some time and others reporting PPK2 working fine now, I will close this. Please open another issue if this occurs again.

**Closed by wlgrd** 2022-03-07 13:31 UTC
